travis:
  secure:
    BINSTAR_TOKEN: QuvNJ+IfoJkovjxSF8kZN5SNkQZPCoS05q8h3kbr8mg0yIBBG3Wz200QhuZSDONnOZIQB9l+M4XrLhB7Dx/QoF/z2GYV6PuW1FhLHik4s0lQBZ5WK+YGO5qJMUqudKmTbQHSTO+2kuRqMrY7edF6M1it767TQP/kAbn0L/AbdwKJA7NG+9svFmI0fxydgdkK/KkLDsswCg7soc8NBnRv8MFjyWUfL8Qvaz1p0f/jL9dhBTFhDgD4oL4bDiDCto2es+0gvtHD1MKbGKt/lB1uBrNiV77tFQwpGKhWFmkhkBGtuCHWFYn6uPphFjKKYAqD0P6xVQZxYtPpBwNMBTxe7vo4ggthEMxrgX3pj752bZFn+Uo+qs6mFXNMAeMQar3s7fpYNSzZHYPqg2ZI117zytCQcRInPlK29HqXfhkBVjsVFC4/eOZkMXsEAil8jihYNfAVY2TrK3PpNGVBNA8fwJtMdabyohAPanQa1tiELoULEjR2LK85acAGXdb4V+wKV6/WHb5kMQo464NEHaHZsnTKg2aPe2jcWfxEvpSThBZxhciDfDj2AoHfdqaA1EvSRq5bCABilzAwmZIGF+yYZBRYCLrljnwRWEV19I0DBDFGawNri4n63wVHRrSbVIZ2v/cKe7fQxEind9SS3wFPJrYj8IjM++6r6zI01Y53RHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
